import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Inter as FontSans } from "next/font/google";
import { cn } from "~/lib/utils";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "~/components/header";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <TRPCReactProvider>
        <Header fontSans={fontSans} />

        <body
          className={cn(
            "bg-background flex flex-col font-sans antialiased",
            fontSans.variable,
          )}
          style={{ height: "calc(100dvh - 45px)" }}
        >
          {children}
        </body>
      </TRPCReactProvider>
    </html>
  );
}
